// Generated by CoffeeScript 1.12.7

/*simple example */

(function() {
  var dance, isFriday, isHappy, smile;

  isHappy = true;

  isFriday = true;

  smile = function() {
    return console.log('Im happy');
  };

  if (isHappy) {
    smile();
  }

  dance = function() {
    return "he is alient";
  };

  console.log(isHappy && isFriday ? dance() : void 0);

}).call(this);
