// Generated by CoffeeScript 1.12.7
(function() {
  var arr, el, i, j, len, print;

  arr = [1, 4, 0, 5, 10, 9];

  print = function(el, i) {
    return console.log("this is " + (i + 1) + "th element with value " + el);
  };

  for (i = j = 0, len = arr.length; j < len; i = ++j) {
    el = arr[i];
    print(el, i);
  }

}).call(this);
