// Generated by CoffeeScript 1.12.7
(function() {
  var gold, rest, setResult, silver, sportsmen,
    slice = [].slice;

  gold = silver = rest = 'unknown';

  setResult = function() {
    var first, other, second;
    first = arguments[0], second = arguments[1], other = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    gold = first;
    silver = second;
    return rest = other;
  };

  sportsmen = [1, 2, 3, 4, 5];

  setResult.apply(null, sportsmen);

  console.log(gold);

  console.log(silver);

  console.log(rest);

}).call(this);
