// Generated by CoffeeScript 1.12.7
(function() {
  var Plane, Vichecle, cessna,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Vichecle = (function() {
    function Vichecle(model, fuel, consuption) {
      this.model = model;
      this.fuel = fuel;
      this.consuption = consuption;
    }

    Vichecle.prototype.tank = function() {
      return console.log(this.model + " has " + this.fuel + " l");
    };

    Vichecle.prototype.moove = function(km) {
      return console.log(this.model + " mooved " + km);
    };

    return Vichecle;

  })();

  Plane = (function(superClass) {
    extend(Plane, superClass);

    function Plane() {
      return Plane.__super__.constructor.apply(this, arguments);
    }

    Plane.prototype.moove = function() {
      console.log("I belive i can fly");
      return Plane.__super__.moove.call(this, 1000);
    };

    return Plane;

  })(Vichecle);

  cessna = new Plane('cessna', '95', 20);

  console.log(cessna.moove());

}).call(this);
